name: tg_erp
description: "A new Flutter project."

publish_to: 'none'



environment:
  sdk: ^3.8.0-278.2.beta


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  image_gallery_saver_plus: ^4.0.1
  firebase_core: ^2.27.0
  cloud_firestore: ^4.13.0
  intl: ^0.18.1



  cupertino_icons: ^1.0.8
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true




