// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgpxY_QfiV5EiTUVzSZCWf0VHBpTuCwrA',
    appId: '1:279524558209:web:25b183c2ea57d4bdcfd480',
    messagingSenderId: '279524558209',
    projectId: 'message-notification-830cc',
    authDomain: 'message-notification-830cc.firebaseapp.com',
    storageBucket: 'message-notification-830cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCNF96wUyHgIrNMh_ijBOGuGXb9uMNegw',
    appId: '1:279524558209:android:af2f5fbdef83789ccfd480',
    messagingSenderId: '279524558209',
    projectId: 'message-notification-830cc',
    storageBucket: 'message-notification-830cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMfgsZN9k6_eZQtR4bnHLJrkfDyPz0_Hk',
    appId: '1:279524558209:ios:120871baa6c59a15cfd480',
    messagingSenderId: '279524558209',
    projectId: 'message-notification-830cc',
    storageBucket: 'message-notification-830cc.firebasestorage.app',
    androidClientId: '279524558209-pq2bfn8525h0bjiijrhfrejcu042ch46.apps.googleusercontent.com',
    iosClientId: '279524558209-lkrjh9ju4064kcdihg1ba5peplitcmm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tgErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMfgsZN9k6_eZQtR4bnHLJrkfDyPz0_Hk',
    appId: '1:279524558209:ios:120871baa6c59a15cfd480',
    messagingSenderId: '279524558209',
    projectId: 'message-notification-830cc',
    storageBucket: 'message-notification-830cc.firebasestorage.app',
    androidClientId: '279524558209-pq2bfn8525h0bjiijrhfrejcu042ch46.apps.googleusercontent.com',
    iosClientId: '279524558209-lkrjh9ju4064kcdihg1ba5peplitcmm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tgErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgpxY_QfiV5EiTUVzSZCWf0VHBpTuCwrA',
    appId: '1:279524558209:web:d9a7c3004bbb5e76cfd480',
    messagingSenderId: '279524558209',
    projectId: 'message-notification-830cc',
    authDomain: 'message-notification-830cc.firebaseapp.com',
    storageBucket: 'message-notification-830cc.firebasestorage.app',
  );
}
